package entities;
// Generated Aug 25, 2014 11:51:24 AM by Hibernate Tools 3.6.0



/**
 * PackageInfo generated by hbm2java
 */
public class PackageInfo  implements java.io.Serializable {


     private int infoId;
     private int packageTours;
     private String content;

    public PackageInfo() {
    }

    public PackageInfo(int infoId, int packageTours, String content) {
       this.infoId = infoId;
       this.packageTours = packageTours;
       this.content = content;
    }
   
    public int getInfoId() {
        return this.infoId;
    }
    
    public void setInfoId(int infoId) {
        this.infoId = infoId;
    }
    public int getPackageTours() {
        return this.packageTours;
    }
    
    public void setPackageTours(int packageTours) {
        this.packageTours = packageTours;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


