package entities;
// Generated Aug 25, 2014 11:51:24 AM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TypePackage generated by hbm2java
 */
public class TypePackage  implements java.io.Serializable {


     private String typeTourisId;
     private String packageName;
     private Set packageTourses = new HashSet(0);

    public TypePackage() {
    }

	
    public TypePackage(String typeTourisId, String packageName) {
        this.typeTourisId = typeTourisId;
        this.packageName = packageName;
    }
    public TypePackage(String typeTourisId, String packageName, Set packageTourses) {
       this.typeTourisId = typeTourisId;
       this.packageName = packageName;
       this.packageTourses = packageTourses;
    }
   
    public String getTypeTourisId() {
        return this.typeTourisId;
    }
    
    public void setTypeTourisId(String typeTourisId) {
        this.typeTourisId = typeTourisId;
    }
    public String getPackageName() {
        return this.packageName;
    }
    
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }
    public Set getPackageTourses() {
        return this.packageTourses;
    }
    
    public void setPackageTourses(Set packageTourses) {
        this.packageTourses = packageTourses;
    }




}


