package g4.east2west.hibernate.objectl;
// Generated Aug 25, 2014 4:26:43 PM by Hibernate Tools 3.6.0



/**
 * PackageInfo generated by hbm2java
 */
public class PackageInfo  implements java.io.Serializable {


     private int infoId;
     private PackageTours packageTours;
     private String content;

    public PackageInfo() {
    }

    public PackageInfo(int infoId, PackageTours packageTours, String content) {
       this.infoId = infoId;
       this.packageTours = packageTours;
       this.content = content;
    }
   
    public int getInfoId() {
        return this.infoId;
    }
    
    public void setInfoId(int infoId) {
        this.infoId = infoId;
    }
    public PackageTours getPackageTours() {
        return this.packageTours;
    }
    
    public void setPackageTours(PackageTours packageTours) {
        this.packageTours = packageTours;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


